version: 2

models:

  - name: stg_etudiants
    description: 
      Vue nettoyée et standardisée de la table étudiants.

    columns:

      - name: user_id
        description: Identifiant utilisateur standardisé (format U-XXX)
        tests:
          - not_null

      - name: path_category_name
        tests:
            - not_null
            
      - name: age_group
        description: Tranche d'âge de l'étudiant 
        tests:
          - not_null

      - name: gender
        description: Genre (M, F, unknown)
        tests:
          - not_null

      - name: region
        description: Région associée à l'étudiant
        tests:
          - not_null

      - name: year_path_started
        description: Année de début du parcours
        tests:
          - not_null


  - name: stg_population2025
    description: 
      Vue nettoyée et standardisée de la table populationbrut.

    columns: 

    - name: region
      description: Région standardisée
      tests:
          - not_null

    - name: gender
      description: Genre (H, F)
      tests:
          - not_null

    - name: age_group
      description: Tranche d'âge par 5 
      tests:
          - not_null

    - name: population
      description: Population agrégée
      tests:
        - not_null