version: 2

models:
  - name: mart_dashboard_evo
    description: "Table consolidée des indicateurs de représentativité (âge, genre, territoire) avec analyse des écarts et classification"

    columns:

      - name: indicator_type
        description: "Type d'indicateur (age, gender, territory)"
        tests:
          - not_null

      - name: dimension
        description: "Dimension associée à l'indicateur (tranche d'âge, genre ou région)"
        tests:
          - not_null

      - name: year
        description: "Année de début du parcours"
        tests:
          - not_null

      - name: index_value
        description: "Valeur de l'indice de représentativité"
        tests:
          - not_null

      - name: indicator_avg
        description: "Moyenne de l'indicateur calculée par type"
        tests:
          - not_null

      - name: gap_to_avg
        description: "Écart entre la valeur de l'indice et la moyenne du type"
        tests:
          - not_null

      - name: status
        description: "Classification de l'indicateur : Underrepresented / Overrepresented / Balanced / Unknown"
        tests:
          - not_null