version: 2

models:
  - name: mart_dashboard_evo
    description: "Table consolidée des indicateurs d'analyse (âge, genre, territoire) permettant d'évaluer la représentativité et la pénétration territoriale"

    columns:

      - name: type_indicateur
        description: "Type d'indicateur analysé (age, genre, territoire)"
        tests:
          - not_null

      - name: dimension
        description: "Dimension associée à l'indicateur (tranche d'âge, genre ou région)"
        tests:
          - not_null

      - name: annee
        description: "Année de début du parcours des étudiants"
        tests:
          - not_null

      - name: metric_type
        description: "Type de métrique utilisée (indice_representativite ou taux_pour_100k)"
        tests:
          - not_null

      - name: valeur_indicateur
        description: "Valeur calculée de la métrique (indice ou taux)"
        tests:
          - not_null

      - name: statut
        description: "Classification analytique : Sous-représenté / Sur-représenté / Pénétration faible / Pénétration forte / Équilibré / Inconnu"
        tests:
          - not_null